[package]
name = "takeoff"
version = "0.1.0"
edition = "2021"
authors = ["Haruki Jay Shimada <peaske16180@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.2.1"

