env:
  node: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jsx-a11y/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - formatjs
  - jsx-a11y
globals:
  localStorage: writable
  document: writable
rules:
  indent:
    - off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  react/prop-types:
    - off
  no-constant-condition:
    - warn
  formatjs/no-offset:
    - warn
